baseURL = "/"
title = "João A. S. Amarante"
theme = "PaperMod"
languageCode = "en-us"
paginate = 10

baseURL = "https://jasamarante.github.io/"

[params]
  author = "João A. S. Amarante"
  description = "Academic website"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2
  
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 3
    
    [[menu.main]]
    name = "Journal Club"
    url = "/jc/"
    weight = 4
  
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
